apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis-kustomization.yaml
- vote-kustomization.yaml
- worker-kustomization.yaml
- db-helmrepository.yaml
- db-helmrelease.yaml
- result-helmrelease.yaml
