apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: instavote
spec:
  interval: 5m
  path: ./kustomize/redis/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
    namespace: instavote
  targetNamespace: instavote
