apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: worker
  namespace: instavote
spec:
  interval: 5m
  path: ./kustomize/worker/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
    namespace: instavote
  targetNamespace: instavote
